services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laboratoria
    ports:
     - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080